sudo: required
addons:
  chrome: stable

language: node_js
node_js:
 #version is read from .nvmrc file
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
- jobs:
  include:
    - stage: lint code
        script:
          - ng lint
    - stage: unit tests
        script:
          - ng test ----source-map=false --browsers=ChromeHeadless --watch=false
    - stage: e2e tests
        script: echo todo add cypress
    - stage: build
        script:
          - ng test ----source-map=false --browsers=ChromeHeadless --watch=false
          - ng build --prod --aot
